#pragma once

namespace Phoenix
{
    //! Hook for Phoenix-side network registration.
    //!
    //! AutoComponent C++ is generated by O3DE Multiplayer from the
    //! *.AutoComponent.xml files under project/Code/Source/AutoGen and is
    //! deliberately not committed; see gems/PhoenixNetworking/Code/Source/AutoGen/README.md.
    void RegisterPhoenixNetworking();
}
